<?php

function nmma_search_form($form, &$form_state) {
  // action
  $form['#action'] = url('the-collection-search');

  // search field.
  $form['name']['combine'] = array(
    '#title' => t('Search'),
    '#type' => 'textfield',
    '#attributes' => array(
      'placeholder' => t('Discover by Artist Name, Title, or Keyword')
    ),
    '#required' => FALSE,
  );

  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
  );

  return $form;
}

function nmma_search_form_submit($form, &$form_state) {
  $combine = $form_state['values']['combine'];
  $form_state['redirect'] = 'the-collection-search?combine=' . urlencode($combine);
}
