<?php

function nmma_search_form($form, &$form_state) {
  // action
  $form['#action'] = url('the-collection-search');
  $form['#method'] = 'get';
  // search field.
  $form['name']['combine'] = array(
    '#title' => t('Search'),
    '#type' => 'textfield',
    '#attributes' => array(
      'placeholder' => t('Discover by Artist Name, Title, or Keyword')
    ),
    '#required' => FALSE,
  );

  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
  );

  return $form;
}

function nmma_search_form_submit($form, &$form_state) {
  drupal_set_message(t('The form has been submitted.',
    array(
      '@combine' => $form_state['values']['combine'],
    )
  ));
}

function hook_menu()
{
	$items ['create_open_access_entry_menu'] = array (
		   'page callback'		=>	'drupal_get_form',
		   'title'				=>	'Open Access Entry form',
		   'page arguments'		=>	array ('open_access_entry_form'),
		   'access arguments'	=>	array ('create open_access_entry_form form' ),
		    'type'				=>	MENU_NORMAL_ITEM
		   );
	return $items;
}

// function hook_theme($existing, $type, $theme, $path){
// 	return array(
//     'open_access_entry_form' => array(
//       'arguments' => array('form' => NULL),
//       'template' => 'templates/forms/open_access_entry_form',
//     ),
//   );
// }

function open_access_form_form($form, &$form_state)
{
  $form['#action'] = '#open_access_form';

  $form['email'] = array(
    '#title' => t('Email address'),
    '#type' => 'textfield',
    '#attributes' => array(
      'placeholder' => t('Email')
    ),
    '#required' => TRUE,
  );

  $form['name']['first'] = array(
    '#title' => t('First Name'),
    '#type' => 'textfield',
    '#attributes' => array(
      'placeholder' => t('First Name')
    ),
    '#required' => TRUE,
  );

  $form['name']['last'] = array(
    '#title' => t('Last Name'),
    '#type' => 'textfield',
    '#attributes' => array(
      'placeholder' => t('Last Name')
    ),
    '#required' => TRUE,
  );

  // $form['theme'] = array(
  //   '#title' => t('Theme'),
  //   '#type' => 'select',
  //   '#options' => array(
  //     'Community',
  //     'Urban Landscape',
  //     'Conceptual / Collage'
  //   )
  // );

  // $form['file'] = array(
  //   '#type' => 'file',
  //   '#title' => t('Image'),
  //   '#description' => t('Upload a file, allowed extensions: jpg, jpeg, png, gif'),
  //   '#required' => TRUE
  // );

  $form['entry_agreement'] = array(
    '#type' => 'checkbox',
    '#title' => t('Replace image with scrolling images from collection. First image shared via google drive Credit line.'),
  );

  $form["buttons"] = array(
      '#value'=>'submit',
      '#type'=>'submit',
      '#attributes' => array('class'=>'btn-add-contact'),
      '#submit'=>array('open_access_entry_form_submit')
  );

  return $form;
}
