<?php

function nmma_search_form($form, &$form_state) {
  // action
  $form['#action'] = url('the-collection-search');
  $form['#method'] = 'get';
  // search field.
  $form['name']['combine'] = array(
    '#title' => t('Search'),
    '#type' => 'textfield',
    '#attributes' => array(
      'placeholder' => t('Discover by Artist Name, Title, or Keyword')
    ),
    '#required' => FALSE,
  );

  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
  );

  return $form;
}

function nmma_search_form_submit($form, &$form_state) {
  drupal_set_message(t('The form has been submitted.',
    array(
      '@combine' => $form_state['values']['combine'],
    )
  ));
}
